# Ejercicio 1 

Sea $f(x) = x^3 - x^2 - x -1 $. 

a.) Queremos hallar la raiz de $f$ usando el método de aproximación de Newton.



In [10]:
using PyPlot

# Función para graficar los valores de x_k y el valor de la raiz. El valor de la raiz corresponde al ultimo elemento de la lista. El valor x indica la condición inicial y n el número de iteraciones que se desee.

function graf_aprox_new(x,n)
    aprox=zeros(n); # Definimos la lista que corresponderá a los valores x_k

    f(x)= x^3 - x^2 - x - 1; # La función y su derivada
    df(x)= 3*x^2 - 2*x -1;
    
    # Ciclo para la lista de los valores x_n usando el método de Newton
    
    for i in 1:n 
        x = x - f(x)/(df(x));
        aprox[i]=x;
    end
   
    # Gráfica de los valores de x_n 
    
    
    scatter(1:n,aprox);
    a = linspace(0,n,100);
    b = aprox[n]*ones(length(a));
    plot(a,b);
    
    xlabel("Iteración");
    ylabel("Valor de x_n");
    title("Método de Newton");
    grid("on");
    
    return show();
    
end

# Función para graficar los valores del error relativo. El valor x indica la condición inicial y n el número de iteraciones que se desee.

function graf_error_rel_new(x,n)
    
    error=zeros(n); # Definimos la lista que corresponderá a los valores de los errores relativos.
    
    f(x)= x^3 - x^2 - x - 1;
    df(x)= 3*x^2 - 2*x -1;
    
    # Ciclo para generar la lista con los valores del error relativo.
    
    for i in 1:n
        y = x - f(x)/(df(x));
        error[i]=abs((x-y)/y);
        x = y
    end
    
    # Gráfica de los errores contra su respectivo número de iteración.
    
    scatter(1:n,error);
    
    xlabel("Iteración");
    ylabel("Error relativo");
    title("Método de Newton");
    grid("on");
    
    return show();
end


graf_error_rel_new (generic function with 1 method)

Graficando el término $x_n$ contra el número de iteraciones así como el error relativo contra el numero de iteraciones para 4 condiciones inciales arbitrarias:

In [11]:
graf_aprox_new(-5, 60)

In [12]:
graf_error_rel_new(-5,60)

In [ ]:
graf_aprox_new(-75, 50)

In [ ]:
graf_error_rel_new(-75, 50)

In [ ]:
graf_aprox_new(-10, 50)

In [ ]:
graf_error_rel_new(-10, 50)

In [ ]:
graf_aprox_new(-200, 60)

In [ ]:
graf_error_rel_new(-200, 60)

b) Hallar la raiz de $f$ usando el método de aproximación de Newton.

In [ ]:
using PyPlot

# Función para graficar los valores de p_n y el valor de la raiz. El valor de la raiz corresponde al ultimo elemento de la lista. Los valores a, b, con a < b indican las condiciones iniciales que son los extremos del intervalo y n el número de iteraciones que se desee.

function graf_aprox_bis(a,b,n)
    
    aprox=zeros(n); # Definimos la lista que corresponderá a los valores x_k

    f(x)= x^3 - x^2 - x - 1; # La función
    
    p = (a+b)/2;

    # Ciclo para la lista de los valores x_n usando el método de bisección
    
    for i in 1:n 
        if f(a)*f(p) > 0
            a = p
        end
        
        if f(b)*f(p) > 0
            b = p
        end
        aprox[i]=p;
        p = (a+b)/2
    end
   
    # Gráfica de los valores de p_n 
    
    scatter(1:n,aprox);
    a = linspace(0,n,100);
    b = aprox[n]*ones(length(a));
    plot(a,b);
    
    xlabel("Iteración");
    ylabel("Valor de p_n");
    title("Método de Bisección");
    grid("on");
    
    return show();
    
end

# Función para graficar los valores del error relativo. Los valores a, b, con a < b indican las condiciones iniciales que son los extremos del intervalo y n el número de iteraciones que se desee.

function graf_error_rel_bis(a,b,n)
    
    error=zeros(n); # Definimos la lista que corresponderá a los valores de los errores relativos.
    
    f(x)= x^3 - x^2 - x - 1;
    
    p = (a+b)/2;
    
    # Ciclo para generar la lista con los valores del error relativo.
    
    for i in 1:n
        if  f(a)*f(p) > 0
            a = p
        end
        
        if f(b)*f(p) > 0
            b = p
        end
        
        error[i]=abs(((a+b)/2 - p)/p);
        p = (a+b)/2
        
    end
    
    # Gráfica de los errores contra su respectivo número de iteración.
    
    scatter(1:n,error);
    
    xlabel("Iteración");
    ylabel("Error relativo");
    title("Método de Bisección");
    grid("on");
    
    return show();
end

In [ ]:
Como con el método de Newton, se hacen las gráficas para 4 intervalos arbitrarios (que contenga a la raiz):

In [ ]:
graf_aprox_bis(-1, 100, 30)

In [ ]:
graf_error_rel_bis(-1, 100, 30)

In [ ]:
graf_aprox_bis(-25, 25, 30)

In [ ]:
graf_error_rel_bis(-25, 25, 30)

In [ ]:
graf_aprox_bis(-27, 10, 30)

In [ ]:
graf_error_rel_bis(-27, 10, 30)

In [ ]:
graf_aprox_bis(0, 10, 30)

In [ ]:
graf_error_rel_bis(0, 10, 30)

# Ejercicio 2



a) Hacer un programa del método de Newton donde la función $f$, $df/dx$ y $x_0$ son los parámetros.

In [17]:
# Se define la función cuya raiz se quiere encontrar así como su derivada

f(x)= x^3 - x^2 - x - 1
df(x) = 3x^2 - 2x - 1

df (generic function with 1 method)

In [18]:
# Método de newton cuyos parámetros con: la función f, su derivada df, una condición inicial x0 y el número de iteraciones n. El valor que regresa es la raiz.

function metodo_newton_2(f,df,x0,n)
    x = x0
    for i in 1:n
        x = x - f(x)/df(x)
    end
    return x
end
        

metodo_newton_2 (generic function with 1 method)

In [19]:
metodo_newton_2(f,df,2, 10)

1.8392867552141612

b) Reemplazar la condición inicial por un rango de condiciones iniciales.

Definamos el rango de condiciones iniciales como:

In [20]:
y=linspace(0.0,10.0,100)

0.0:0.10101010101010101:10.0

Usando la misma función del inciso anterior pero agregando `.` entre el nombre de la función y el paréntesis para que al función sea evaluada sobre un vector:

In [53]:
metodo_newton_2.(f,df,y,25)

100-element Array{Float64,1}:
  1.83929 
  1.83929 
  1.83929 
  1.83929 
 -0.892283
  1.83933 
  0.93016 
  1.83929 
  1.83929 
  1.83929 
 -1.02428 
  1.84583 
  1.83929 
  ⋮       
  1.83929 
  1.83929 
  1.83929 
  1.83929 
  1.83929 
  1.83929 
  1.83929 
  1.83929 
  1.83929 
  1.83929 
  1.83929 
  1.83929 

c) Ahora, el método de Newton cuyas condiciones iniciales están dadas por un `linspace` y muestre un arreglo los términos cuya diferencia a la raiz sea menor a e. Definamos el rango de condiciones como:

In [54]:
y=linspace(0.0,10.0,100)

0.0:0.10101010101010101:10.0

In [55]:
# Buscamos la raices diferentes entre si que además su diferencia de la raiz real es menor a un número e. Lo siguiente es para eliminar las raices repetidas del arreglo anterior.

function metodo_newton_3(z,e)
    
    arreglo = metodo_newton_2.(f,df,z,100)
    t=[]
    
    push!(t,arreglo[1])
    for i in 1:length(arreglo)
        indice = 0
        
        for j in 1:length(t)
            
            if arreglo[i] > t[j] + e
                indice = indice + 1
            end
            
            if arreglo[i] < t[j] -e
                indice = indice + 1
            end
        end
        
        if indice == length(t)
            push!(t,arreglo[i])
        end
    end
return t
end

metodo_newton_3 (generic function with 1 method)

In [56]:
metodo_newton_3(y,0.00000001)

1-element Array{Any,1}:
 1.83929

d) Finalmente, desarrollar una función similar a la anterior, siguiendo los mismos pasos, pero esta vez que los _inputs_ de la función del método sean solamente la función y la condición inicial:

In [57]:
using SymPy

x = symbols("x")

x

In [58]:
# Condiciones iniciales:
    
n = 200
g(x) = x^2 - 5
er = 0.00000001



# Esta es la función que se encarga de convertir nuestra función g(x) en una función SymPy, para luego derivarlo y regresar la derivada como una función de Julia. Posteriormente se aplica el método de Newton a la condición inicial.

function root(g,y)
    
    f = g(x) 
    df = diff(g(x),x) # Derivamos la función de SymPy 
    dg = lambdify(df,[x]) # Regresamos la función de SymPy a una función de Julia
    
    # Método de Newton sobre la condición incial
    
    for i in 1:n
        y = y - g(y)/dg(y)
    end
    return y
    
end

# Esta función se recicla del inciso anterior para eliminar las raices repetidas del arreglo `linspace`

function metodo_newton4(g,y)
    
    arreglo = root.(g,y)
    t=[]
    
    push!(t,arreglo[1])
    for i in 1:length(arreglo)
        indice = 0
        
        for j in 1:length(t)
            
            if arreglo[i] > t[j] + er
                indice = indice + 1
            end
            
            if arreglo[i] < t[j] - er
                indice = indice + 1
            end
        end
        
        if indice == length(t)
            push!(t,arreglo[i])
        end
    end
    
# Esta es el arreglo que contiene las raices no repetidas de nuestra función g(x)
return t
end

metodo_newton4 (generic function with 1 method)

In [59]:
y = linspace(-10,10,100)

-10.0:0.20202020202020202:10.0

In [60]:
metodo_newton4(g,y)

2-element Array{Any,1}:
 -2.23607
  2.23607